using MCBEEditor.Core.Chunk;
namespace MCBEEditor.Core.World;
public sealed record BedrockDataValueEntry(int Id, string Identifier, string DisplayName)
{
    public string HexadecimalId => $"0x{unchecked((uint)Id):X2}";
}
public static class BedrockDataValueCatalog
{
    public static readonly IReadOnlyList<BedrockDataValueEntry> Entities =
    [
        new(1, "minecraft:undefined_test_only", "仅测试未定义实体"),
        new(10, "minecraft:chicken", "鸡"),
        new(11, "minecraft:cow", "牛"),
        new(12, "minecraft:pig", "猪"),
        new(13, "minecraft:sheep", "绵羊"),
        new(14, "minecraft:wolf", "狼"),
        new(15, "minecraft:villager", "村民（旧版）"),
        new(16, "minecraft:mooshroom", "哞菇"),
        new(17, "minecraft:squid", "鱿鱼"),
        new(18, "minecraft:rabbit", "兔子"),
        new(19, "minecraft:bat", "蝙蝠"),
        new(20, "minecraft:iron_golem", "铁傀儡"),
        new(21, "minecraft:snow_golem", "雪傀儡"),
        new(22, "minecraft:ocelot", "豹猫"),
        new(23, "minecraft:horse", "马"),
        new(24, "minecraft:donkey", "驴"),
        new(25, "minecraft:mule", "骡"),
        new(26, "minecraft:skeleton_horse", "骷髅马"),
        new(27, "minecraft:zombie_horse", "僵尸马"),
        new(28, "minecraft:polar_bear", "北极熊"),
        new(29, "minecraft:llama", "羊驼"),
        new(30, "minecraft:parrot", "鹦鹉"),
        new(31, "minecraft:dolphin", "海豚"),
        new(32, "minecraft:zombie", "僵尸"),
        new(33, "minecraft:creeper", "苦力怕"),
        new(34, "minecraft:skeleton", "骷髅"),
        new(35, "minecraft:spider", "蜘蛛"),
        new(36, "minecraft:zombie_pigman", "僵尸猪灵"),
        new(37, "minecraft:slime", "史莱姆"),
        new(38, "minecraft:enderman", "末影人"),
        new(39, "minecraft:silverfish", "蠹虫"),
        new(40, "minecraft:cave_spider", "洞穴蜘蛛"),
        new(41, "minecraft:ghast", "恶魂"),
        new(42, "minecraft:magma_cube", "岩浆怪"),
        new(43, "minecraft:blaze", "烈焰人"),
        new(44, "minecraft:zombie_villager", "僵尸村民（旧版）"),
        new(45, "minecraft:witch", "女巫"),
        new(46, "minecraft:stray", "流浪者"),
        new(47, "minecraft:husk", "尸壳"),
        new(48, "minecraft:wither_skeleton", "凋灵骷髅"),
        new(49, "minecraft:guardian", "守卫者"),
        new(50, "minecraft:elder_guardian", "远古守卫者"),
        new(51, "minecraft:npc", "NPC"),
        new(52, "minecraft:wither", "凋灵"),
        new(53, "minecraft:ender_dragon", "末影龙"),
        new(54, "minecraft:shulker", "潜影贝"),
        new(55, "minecraft:endermite", "末影螨"),
        new(56, "minecraft:agent", "智能体"),
        new(57, "minecraft:vindicator", "卫道士"),
        new(58, "minecraft:phantom", "幻翼"),
        new(59, "minecraft:ravager", "劫掠兽"),
        new(61, "minecraft:armor_stand", "盔甲架"),
        new(62, "minecraft:tripod_camera", "相机"),
        new(63, "minecraft:player", "玩家"),
        new(64, "minecraft:item", "掉落物"),
        new(65, "minecraft:tnt", "点燃的 TNT"),
        new(66, "minecraft:falling_block", "下落的方块"),
        new(67, "minecraft:moving_block", "移动的方块"),
        new(68, "minecraft:xp_bottle", "附魔之瓶"),
        new(69, "minecraft:xp_orb", "经验球"),
        new(70, "minecraft:eye_of_ender_signal", "末影之眼"),
        new(71, "minecraft:ender_crystal", "末地水晶"),
        new(72, "minecraft:fireworks_rocket", "烟花火箭"),
        new(73, "minecraft:thrown_trident", "三叉戟"),
        new(74, "minecraft:turtle", "海龟"),
        new(75, "minecraft:cat", "猫"),
        new(76, "minecraft:shulker_bullet", "潜影弹"),
        new(77, "minecraft:fishing_hook", "浮漂"),
        new(78, "minecraft:chalkboard", "黑板"),
        new(79, "minecraft:dragon_fireball", "末影龙火球"),
        new(80, "minecraft:arrow", "箭"),
        new(81, "minecraft:snowball", "雪球"),
        new(82, "minecraft:egg", "鸡蛋"),
        new(83, "minecraft:painting", "画"),
        new(84, "minecraft:minecart", "矿车"),
        new(85, "minecraft:fireball", "火球"),
        new(86, "minecraft:splash_potion", "喷溅药水"),
        new(87, "minecraft:ender_pearl", "末影珍珠"),
        new(88, "minecraft:leash_knot", "拴绳结"),
        new(89, "minecraft:wither_skull", "凋灵之首"),
        new(90, "minecraft:boat", "船"),
        new(91, "minecraft:wither_skull_dangerous", "蓝色凋灵之首"),
        new(93, "minecraft:lightning_bolt", "闪电"),
        new(94, "minecraft:small_fireball", "小火球"),
        new(95, "minecraft:area_effect_cloud", "区域效果云"),
        new(96, "minecraft:hopper_minecart", "漏斗矿车"),
        new(97, "minecraft:tnt_minecart", "TNT 矿车"),
        new(98, "minecraft:chest_minecart", "运输矿车"),
        new(100, "minecraft:command_block_minecart", "命令方块矿车"),
        new(101, "minecraft:lingering_potion", "滞留药水"),
        new(102, "minecraft:llama_spit", "羊驼唾沫"),
        new(103, "minecraft:evocation_fang", "尖牙"),
        new(104, "minecraft:evocation_illager", "唤魔者"),
        new(105, "minecraft:vex", "恼鬼"),
        new(106, "minecraft:ice_bomb", "冰弹"),
        new(107, "minecraft:balloon", "气球"),
        new(108, "minecraft:pufferfish", "河豚"),
        new(109, "minecraft:salmon", "鲑鱼"),
        new(110, "minecraft:drowned", "溺尸"),
        new(111, "minecraft:tropicalfish", "热带鱼"),
        new(112, "minecraft:cod", "鳕鱼"),
        new(113, "minecraft:panda", "熊猫"),
        new(114, "minecraft:pillager", "掠夺者"),
        new(115, "minecraft:villager_v2", "村民"),
        new(116, "minecraft:zombie_villager_v2", "僵尸村民"),
        new(117, "minecraft:shield", "盾牌"),
        new(118, "minecraft:wandering_trader", "流浪商人"),
        new(120, "minecraft:elder_guardian_ghost", "远古守卫者幽灵"),
        new(121, "minecraft:fox", "狐狸"),
        new(122, "minecraft:bee", "蜜蜂"),
        new(123, "minecraft:piglin", "猪灵"),
        new(124, "minecraft:hoglin", "疣猪兽"),
        new(125, "minecraft:strider", "炽足兽"),
        new(126, "minecraft:zoglin", "僵尸疣猪兽"),
        new(127, "minecraft:piglin_brute", "猪灵蛮兵"),
        new(128, "minecraft:goat", "山羊"),
        new(129, "minecraft:glow_squid", "发光鱿鱼"),
        new(130, "minecraft:axolotl", "美西螈"),
        new(131, "minecraft:warden", "监守者"),
        new(132, "minecraft:frog", "青蛙"),
        new(133, "minecraft:tadpole", "蝌蚪"),
        new(134, "minecraft:allay", "悦灵"),
        new(138, "minecraft:camel", "骆驼"),
        new(139, "minecraft:sniffer", "嗅探兽"),
        new(140, "minecraft:breeze", "旋风人"),
        new(141, "minecraft:breeze_wind_charge_projectile", "旋风弹"),
        new(142, "minecraft:armadillo", "犰狳"),
        new(143, "minecraft:wind_charge_projectile", "风弹"),
        new(144, "minecraft:bogged", "沼骸"),
        new(145, "minecraft:ominous_item_spawner", "不祥之物生成器"),
        new(146, "minecraft:creaking", "嘎枝"),
        new(147, "minecraft:happy_ghast", "快乐恶魂"),
        new(148, "minecraft:copper_golem", "铜傀儡"),
        new(149, "minecraft:nautilus", "鹦鹉螺"),
        new(150, "minecraft:zombie_nautilus", "僵尸鹦鹉螺"),
        new(151, "minecraft:parched", "焦骸"),
        new(152, "minecraft:camel_husk", "骆驼尸壳"),
        new(153, "minecraft:sulfur_cube", "硫方怪"),
        new(154, "minecraft:cushion", "坐垫"),
        new(157, "minecraft:trader_llama", "行商羊驼"),
        new(218, "minecraft:chest_boat", "运输船"),
    ];

    public static readonly IReadOnlyList<BedrockDataValueEntry> StatusEffects =
    [
        new(1, "speed", "迅捷"),
        new(2, "slowness", "缓慢"),
        new(3, "haste", "急迫"),
        new(4, "mining_fatigue", "挖掘疲劳"),
        new(5, "strength", "力量"),
        new(6, "instant_health", "瞬间治疗"),
        new(7, "instant_damage", "瞬间伤害"),
        new(8, "jump_boost", "跳跃提升"),
        new(9, "nausea", "反胃"),
        new(10, "regeneration", "生命恢复"),
        new(11, "resistance", "抗性提升"),
        new(12, "fire_resistance", "抗火"),
        new(13, "water_breathing", "水下呼吸"),
        new(14, "invisibility", "隐身"),
        new(15, "blindness", "失明"),
        new(16, "night_vision", "夜视"),
        new(17, "hunger", "饥饿"),
        new(18, "weakness", "虚弱"),
        new(19, "poison", "中毒"),
        new(20, "wither", "凋零"),
        new(21, "health_boost", "生命提升"),
        new(22, "absorption", "伤害吸收"),
        new(23, "saturation", "饱和"),
        new(24, "levitation", "飘浮"),
        new(25, "fatal_poison", "中毒（致命）"),
        new(26, "conduit_power", "潮涌能量"),
        new(27, "slow_falling", "缓降"),
        new(28, "bad_omen", "不祥之兆"),
        new(29, "village_hero", "村庄英雄"),
        new(30, "darkness", "黑暗"),
        new(31, "trial_omen", "试炼之兆"),
        new(32, "wind_charged", "蓄风"),
        new(33, "weaving", "盘丝"),
        new(34, "oozing", "渗浆"),
        new(35, "infested", "寄生"),
        new(36, "raid_omen", "袭击之兆"),
        new(37, "breath_of_the_nautilus", "鹦鹉螺之息"),
    ];

    public static readonly IReadOnlyList<BedrockDataValueEntry> Enchantments =
    [
        new(0, "protection", "保护"),
        new(1, "fire_protection", "火焰保护"),
        new(2, "feather_falling", "摔落缓冲"),
        new(3, "blast_protection", "爆炸保护"),
        new(4, "projectile_protection", "弹射物保护"),
        new(5, "thorns", "荆棘"),
        new(6, "respiration", "水下呼吸"),
        new(7, "depth_strider", "深海探索者"),
        new(8, "aqua_affinity", "水下速掘"),
        new(9, "sharpness", "锋利"),
        new(10, "smite", "亡灵杀手"),
        new(11, "bane_of_arthropods", "节肢杀手"),
        new(12, "knockback", "击退"),
        new(13, "fire_aspect", "火焰附加"),
        new(14, "looting", "抢夺"),
        new(15, "efficiency", "效率"),
        new(16, "silk_touch", "精准采集"),
        new(17, "unbreaking", "耐久"),
        new(18, "fortune", "时运"),
        new(19, "power", "力量"),
        new(20, "punch", "冲击"),
        new(21, "flame", "火矢"),
        new(22, "infinity", "无限"),
        new(23, "luck_of_the_sea", "海之眷顾"),
        new(24, "lure", "饵钓"),
        new(25, "frost_walker", "冰霜行者"),
        new(26, "mending", "经验修补"),
        new(27, "binding_curse", "绑定诅咒"),
        new(28, "vanishing_curse", "消失诅咒"),
        new(29, "impaling", "穿刺"),
        new(30, "riptide", "激流"),
        new(31, "loyalty", "忠诚"),
        new(32, "channeling", "引雷"),
        new(33, "multishot", "多重射击"),
        new(34, "piercing", "穿透"),
        new(35, "quick_charge", "快速装填"),
        new(36, "soul_speed", "灵魂疾行"),
        new(37, "swift_sneak", "迅捷潜行"),
        new(38, "wind_burst", "风爆"),
        new(39, "density", "致密"),
        new(40, "breach", "破甲"),
        new(41, "lunge", "突进"),
    ];

    public static readonly IReadOnlyList<BedrockDataValueEntry> LegacyBlocks =
    [
        new(0, "minecraft:air", "air"),
        new(1, "minecraft:stone", "stone"),
        new(2, "minecraft:grass", "grass block"),
        new(3, "minecraft:dirt", "dirt"),
        new(4, "minecraft:cobblestone", "cobblestone"),
        new(5, "minecraft:planks", "wooden planks"),
        new(6, "minecraft:sapling", "sapling"),
        new(7, "minecraft:bedrock", "bedrock"),
        new(8, "minecraft:flowing_water", "flowing water"),
        new(9, "minecraft:water", "water"),
        new(10, "minecraft:flowing_lava", "flowing lava"),
        new(11, "minecraft:lava", "lava"),
        new(12, "minecraft:sand", "sand"),
        new(13, "minecraft:gravel", "gravel"),
        new(14, "minecraft:gold_ore", "gold ore"),
        new(15, "minecraft:iron_ore", "iron ore"),
        new(16, "minecraft:coal_ore", "coal ore"),
        new(17, "minecraft:log", "log"),
        new(18, "minecraft:leaves", "leaves"),
        new(19, "minecraft:sponge", "sponge"),
        new(20, "minecraft:glass", "glass"),
        new(21, "minecraft:lapis_ore", "lapis ore"),
        new(22, "minecraft:lapis_block", "lapis block"),
        new(23, "minecraft:dispenser", "dispenser"),
        new(24, "minecraft:sandstone", "sandstone"),
        new(25, "minecraft:noteblock", "noteblock"),
        new(26, "minecraft:bed", "bed"),
        new(27, "minecraft:golden_rail", "golden rail"),
        new(28, "minecraft:detector_rail", "detector rail"),
        new(29, "minecraft:sticky_piston", "sticky piston"),
        new(30, "minecraft:web", "web"),
        new(31, "minecraft:tallgrass", "tall grass"),
        new(32, "minecraft:deadbush", "deadbush"),
        new(33, "minecraft:piston", "piston"),
        new(34, "minecraft:pistonArmCollision", "piston arm collision"),
        new(35, "minecraft:wool", "wool"),
        new(36, "minecraft:element_0", "element 0"),
        new(37, "minecraft:yellow_flower", "yellow flower"),
        new(38, "minecraft:red_flower", "red flower"),
        new(39, "minecraft:brown_mushroom", "brown mushroom"),
        new(40, "minecraft:red_mushroom", "red mushroom"),
        new(41, "minecraft:gold_block", "gold block"),
        new(42, "minecraft:iron_block", "iron block"),
        new(43, "minecraft:double_stone_slab", "double stone slab"),
        new(44, "minecraft:stone_slab", "stone slab"),
        new(45, "minecraft:brick_block", "brick block"),
        new(46, "minecraft:tnt", "tnt"),
        new(47, "minecraft:bookshelf", "bookshelf"),
        new(48, "minecraft:mossy_cobblestone", "mossy cobblestone"),
        new(49, "minecraft:obsidian", "obsidian"),
        new(50, "minecraft:torch", "torch"),
        new(51, "minecraft:fire", "fire"),
        new(52, "minecraft:mob_spawner", "mob spawner"),
        new(53, "minecraft:oak_stairs", "oak stairs"),
        new(54, "minecraft:chest", "chest"),
        new(55, "minecraft:redstone_wire", "redstone wire"),
        new(56, "minecraft:diamond_ore", "diamond ore"),
        new(57, "minecraft:diamond_block", "diamond block"),
        new(58, "minecraft:crafting_table", "crafting table"),
        new(59, "minecraft:wheat", "wheat"),
        new(60, "minecraft:farmland", "farmland"),
        new(61, "minecraft:furnace", "furnace"),
        new(62, "minecraft:lit_furnace", "lit furnace"),
        new(63, "minecraft:standing_sign", "standing sign"),
        new(64, "minecraft:wooden_door", "wooden door"),
        new(65, "minecraft:ladder", "ladder"),
        new(66, "minecraft:rail", "rail"),
        new(67, "minecraft:stone_stairs", "stone stairs"),
        new(68, "minecraft:wall_sign", "wall sign"),
        new(69, "minecraft:lever", "lever"),
        new(70, "minecraft:stone_pressure_plate", "stone pressure plate"),
        new(71, "minecraft:iron_door", "iron door"),
        new(72, "minecraft:wooden_pressure_plate", "wooden pressure plate"),
        new(73, "minecraft:redstone_ore", "redstone ore"),
        new(74, "minecraft:lit_redstone_ore", "lit redstone ore"),
        new(75, "minecraft:unlit_redstone_torch", "unlit redstone torch"),
        new(76, "minecraft:redstone_torch", "redstone torch"),
        new(77, "minecraft:stone_button", "stone button"),
        new(78, "minecraft:snow_layer", "snow layer"),
        new(79, "minecraft:ice", "ice"),
        new(80, "minecraft:snow", "snow"),
        new(81, "minecraft:cactus", "cactus"),
        new(82, "minecraft:clay", "clay"),
        new(83, "minecraft:reeds", "reeds"),
        new(84, "minecraft:jukebox", "jukebox"),
        new(85, "minecraft:fence", "fence"),
        new(86, "minecraft:pumpkin", "pumpkin"),
        new(87, "minecraft:netherrack", "netherrack"),
        new(88, "minecraft:soul_sand", "soul sand"),
        new(89, "minecraft:glowstone", "glowstone"),
        new(90, "minecraft:portal", "portal"),
        new(91, "minecraft:lit_pumpkin", "lit pumpkin"),
        new(92, "minecraft:cake", "cake"),
        new(93, "minecraft:unpowered_repeater", "unpowered repeater"),
        new(94, "minecraft:powered_repeater", "powered repeater"),
        new(95, "minecraft:invisibleBedrock", "invisible bedrock"),
        new(96, "minecraft:trapdoor", "trapdoor"),
        new(97, "minecraft:monster_egg", "monster egg"),
        new(98, "minecraft:stonebrick", "stone bricks"),
        new(99, "minecraft:brown_mushroom_block", "brown mushroom block"),
        new(100, "minecraft:red_mushroom_block", "red mushroom block"),
        new(101, "minecraft:iron_bars", "iron bars"),
        new(102, "minecraft:glass_pane", "glass pane"),
        new(103, "minecraft:melon_block", "melon block"),
        new(104, "minecraft:pumpkin_stem", "pumpkin stem"),
        new(105, "minecraft:melon_stem", "melon stem"),
        new(106, "minecraft:vine", "vine"),
        new(107, "minecraft:fence_gate", "fence gate"),
        new(108, "minecraft:brick_stairs", "brick stairs"),
        new(109, "minecraft:stone_brick_stairs", "stone brick stairs"),
        new(110, "minecraft:mycelium", "mycelium"),
        new(111, "minecraft:waterlily", "waterlily"),
        new(112, "minecraft:nether_brick", "nether brick"),
        new(113, "minecraft:nether_brick_fence", "nether brick fence"),
        new(114, "minecraft:nether_brick_stairs", "nether brick stairs"),
        new(115, "minecraft:nether_wart", "nether wart"),
        new(116, "minecraft:enchanting_table", "enchanting table"),
        new(117, "minecraft:brewing_stand", "brewing stand"),
        new(118, "minecraft:cauldron", "cauldron"),
        new(119, "minecraft:end_portal", "end portal"),
        new(120, "minecraft:end_portal_frame", "end portal frame"),
        new(121, "minecraft:end_stone", "end stone"),
        new(122, "minecraft:dragon_egg", "dragon egg"),
        new(123, "minecraft:redstone_lamp", "redstone lamp"),
        new(124, "minecraft:lit_redstone_lamp", "lit redstone lamp"),
        new(125, "minecraft:dropper", "dropper"),
        new(126, "minecraft:activator_rail", "activator rail"),
        new(127, "minecraft:cocoa", "cocoa"),
        new(128, "minecraft:sandstone_stairs", "sandstone stairs"),
        new(129, "minecraft:emerald_ore", "emerald ore"),
        new(130, "minecraft:ender_chest", "ender chest"),
        new(131, "minecraft:tripwire_hook", "tripwire hook"),
        new(132, "minecraft:tripWire", "tripwire"),
        new(133, "minecraft:emerald_block", "emerald block"),
        new(134, "minecraft:spruce_stairs", "spruce stairs"),
        new(135, "minecraft:birch_stairs", "birch stairs"),
        new(136, "minecraft:jungle_stairs", "jungle stairs"),
        new(137, "minecraft:command_block", "command block"),
        new(138, "minecraft:beacon", "beacon"),
        new(139, "minecraft:cobblestone_wall", "cobblestone wall"),
        new(140, "minecraft:flower_pot", "flower pot"),
        new(141, "minecraft:carrots", "carrots"),
        new(142, "minecraft:potatoes", "potatoes"),
        new(143, "minecraft:wooden_button", "wooden button"),
        new(144, "minecraft:skull", "skull"),
        new(145, "minecraft:anvil", "anvil"),
        new(146, "minecraft:trapped_chest", "trapped chest"),
        new(147, "minecraft:light_weighted_pressure_plate", "light weighted pressure plate"),
        new(148, "minecraft:heavy_weighted_pressure_plate", "heavy weighted pressure plate"),
        new(149, "minecraft:unpowered_comparator", "unpowered comparator"),
        new(150, "minecraft:powered_comparator", "powered comparator"),
        new(151, "minecraft:daylight_detector", "daylight detector"),
        new(152, "minecraft:redstone_block", "redstone block"),
        new(153, "minecraft:quartz_ore", "quartz ore"),
        new(154, "minecraft:hopper", "hopper"),
        new(155, "minecraft:quartz_block", "quartz block"),
        new(156, "minecraft:quartz_stairs", "quartz stairs"),
        new(157, "minecraft:double_wooden_slab", "double wooden slab"),
        new(158, "minecraft:wooden_slab", "wooden slab"),
        new(159, "minecraft:stained_hardened_clay", "stained hardened clay"),
        new(160, "minecraft:stained_glass_pane", "stained glass pane"),
        new(161, "minecraft:leaves2", "leaves 2"),
        new(162, "minecraft:log2", "log 2"),
        new(163, "minecraft:acacia_stairs", "acacia stairs"),
        new(164, "minecraft:dark_oak_stairs", "dark oak stairs"),
        new(165, "minecraft:slime", "slime"),
        new(166, "minecraft:unused_166", "未使用"),
        new(167, "minecraft:iron_trapdoor", "iron trapdoor"),
        new(168, "minecraft:prismarine", "prismarine"),
        new(169, "minecraft:seaLantern", "sea lantern"),
        new(170, "minecraft:hay_block", "hay block"),
        new(171, "minecraft:carpet", "carpet"),
        new(172, "minecraft:hardened_clay", "hardened clay"),
        new(173, "minecraft:coal_block", "coal block"),
        new(174, "minecraft:packed_ice", "packed ice"),
        new(175, "minecraft:double_plant", "double plant"),
        new(176, "minecraft:standing_banner", "standing banner"),
        new(177, "minecraft:wall_banner", "wall banner"),
        new(178, "minecraft:daylight_detector_inverted", "daylight detector inverted"),
        new(179, "minecraft:red_sandstone", "red sandstone"),
        new(180, "minecraft:red_sandstone_stairs", "red sandstone stairs"),
        new(181, "minecraft:double_stone_slab2", "double stone slab 2"),
        new(182, "minecraft:stone_slab2", "stone slab 2"),
        new(183, "minecraft:spruce_fence_gate", "spruce fence gate"),
        new(184, "minecraft:birch_fence_gate", "birch fence gate"),
        new(185, "minecraft:jungle_fence_gate", "jungle fence gate"),
        new(186, "minecraft:dark_oak_fence_gate", "dark oak fence gate"),
        new(187, "minecraft:acacia_fence_gate", "acacia fence gate"),
        new(188, "minecraft:repeating_command_block", "repeating command block"),
        new(189, "minecraft:chain_command_block", "chain command block"),
        new(190, "minecraft:hard_glass_pane", "hard glass pane"),
        new(191, "minecraft:hard_stained_glass_pane", "hard stained glass pane"),
        new(192, "minecraft:chemical_heat", "chemical heat"),
        new(193, "minecraft:spruce_door", "spruce door"),
        new(194, "minecraft:birch_door", "birch door"),
        new(195, "minecraft:jungle_door", "jungle door"),
        new(196, "minecraft:acacia_door", "acacia door"),
        new(197, "minecraft:dark_oak_door", "dark oak door"),
        new(198, "minecraft:grass_path", "grass path"),
        new(199, "minecraft:frame", "frame"),
        new(200, "minecraft:chorus_flower", "chorus flower"),
        new(201, "minecraft:purpur_block", "purpur block"),
        new(202, "minecraft:colored_torch_rg", "colored torch RG"),
        new(203, "minecraft:purpur_stairs", "purpur stairs"),
        new(204, "minecraft:colored_torch_bp", "colored torch BP"),
        new(205, "minecraft:undyed_shulker_box", "undyed shulker box"),
        new(206, "minecraft:end_bricks", "end bricks"),
        new(207, "minecraft:frosted_ice", "frosted ice"),
        new(208, "minecraft:end_rod", "end rod"),
        new(209, "minecraft:end_gateway", "end gateway"),
        new(210, "minecraft:allow", "allow"),
        new(211, "minecraft:deny", "deny"),
        new(212, "minecraft:border_block", "border block"),
        new(213, "minecraft:magma", "magma"),
        new(214, "minecraft:nether_wart_block", "nether wart block"),
        new(215, "minecraft:red_nether_brick", "red nether brick"),
        new(216, "minecraft:bone_block", "bone block"),
        new(217, "minecraft:structure_void", "structure void"),
        new(218, "minecraft:shulker_box", "shulker box"),
        new(219, "minecraft:purple_glazed_terracotta", "purple glazed terracotta"),
        new(220, "minecraft:white_glazed_terracotta", "white glazed terracotta"),
        new(221, "minecraft:orange_glazed_terracotta", "orange glazed terracotta"),
        new(222, "minecraft:magenta_glazed_terracotta", "magenta glazed terracotta"),
        new(223, "minecraft:light_blue_glazed_terracotta", "light blue glazed terracotta"),
        new(224, "minecraft:yellow_glazed_terracotta", "yellow glazed terracotta"),
        new(225, "minecraft:lime_glazed_terracotta", "lime glazed terracotta"),
        new(226, "minecraft:pink_glazed_terracotta", "pink glazed terracotta"),
        new(227, "minecraft:gray_glazed_terracotta", "gray glazed terracotta"),
        new(228, "minecraft:silver_glazed_terracotta", "silver glazed terracotta"),
        new(229, "minecraft:cyan_glazed_terracotta", "cyan glazed terracotta"),
        new(230, "minecraft:chalkboard", "chalkboard"),
        new(231, "minecraft:blue_glazed_terracotta", "blue glazed terracotta"),
        new(232, "minecraft:brown_glazed_terracotta", "brown glazed terracotta"),
        new(233, "minecraft:green_glazed_terracotta", "green glazed terracotta"),
        new(234, "minecraft:red_glazed_terracotta", "red glazed terracotta"),
        new(235, "minecraft:black_glazed_terracotta", "black glazed terracotta"),
        new(236, "minecraft:concrete", "concrete"),
        new(237, "minecraft:concretePowder", "concrete powder"),
        new(238, "minecraft:chemistry_table", "chemistry table"),
        new(239, "minecraft:underwater_torch", "underwater torch"),
        new(240, "minecraft:chorus_plant", "chorus plant"),
        new(241, "minecraft:stained_glass", "stained glass"),
        new(242, "minecraft:camera", "camera"),
        new(243, "minecraft:podzol", "podzol"),
        new(244, "minecraft:beetroot", "beetroot"),
        new(245, "minecraft:stonecutter", "stonecutter"),
        new(246, "minecraft:glowingobsidian", "glowingobsidian"),
        new(247, "minecraft:netherreactor", "netherreactor"),
        new(248, "minecraft:info_update", "info update"),
        new(249, "minecraft:info_update2", "info update2"),
        new(250, "minecraft:movingBlock", "moving block"),
        new(251, "minecraft:observer", "observer"),
        new(252, "minecraft:structure_block", "structure block"),
        new(253, "minecraft:hard_glass", "hard glass"),
        new(254, "minecraft:hard_stained_glass", "hard stained glass"),
        new(255, "minecraft:reserved6", "reserved6"),
    ];

    public static IReadOnlyList<BedrockDataValueEntry> Biomes => BedrockBiomeCatalog.Entries
        .Select(entry => new BedrockDataValueEntry(unchecked((int)entry.Id), entry.Identifier, entry.DisplayName))
        .ToArray();

    public static IReadOnlyList<BedrockDataValueEntry> Search(IEnumerable<BedrockDataValueEntry> entries, string? rawQuery)
    {
        var query = (rawQuery ?? string.Empty).Trim();
        if (query.Length == 0) return entries.ToArray();
        return entries.Where(entry =>
            entry.Id.ToString(System.Globalization.CultureInfo.InvariantCulture).Contains(query, StringComparison.OrdinalIgnoreCase)
            || entry.HexadecimalId.Contains(query, StringComparison.OrdinalIgnoreCase)
            || entry.Identifier.Contains(query, StringComparison.OrdinalIgnoreCase)
            || entry.DisplayName.Contains(query, StringComparison.OrdinalIgnoreCase)).ToArray();
    }
}
