import Foundation
/// Legacy Bedrock block numeric IDs (0...255) and their matching legacy string IDs.
/// Numeric IDs are used by old subchunk storage; modern aliases are accepted for lookup.
enum BedrockLegacyBlockCatalog {
    static let blocks: [BedrockDataValueEntry] = [
        BedrockDataValueEntry(id: 0, identifier: "minecraft:air", displayName: "air"),
        BedrockDataValueEntry(id: 1, identifier: "minecraft:stone", displayName: "stone"),
        BedrockDataValueEntry(id: 2, identifier: "minecraft:grass", displayName: "grass block"),
        BedrockDataValueEntry(id: 3, identifier: "minecraft:dirt", displayName: "dirt"),
        BedrockDataValueEntry(id: 4, identifier: "minecraft:cobblestone", displayName: "cobblestone"),
        BedrockDataValueEntry(id: 5, identifier: "minecraft:planks", displayName: "wooden planks"),
        BedrockDataValueEntry(id: 6, identifier: "minecraft:sapling", displayName: "sapling"),
        BedrockDataValueEntry(id: 7, identifier: "minecraft:bedrock", displayName: "bedrock"),
        BedrockDataValueEntry(id: 8, identifier: "minecraft:flowing_water", displayName: "flowing water"),
        BedrockDataValueEntry(id: 9, identifier: "minecraft:water", displayName: "water"),
        BedrockDataValueEntry(id: 10, identifier: "minecraft:flowing_lava", displayName: "flowing lava"),
        BedrockDataValueEntry(id: 11, identifier: "minecraft:lava", displayName: "lava"),
        BedrockDataValueEntry(id: 12, identifier: "minecraft:sand", displayName: "sand"),
        BedrockDataValueEntry(id: 13, identifier: "minecraft:gravel", displayName: "gravel"),
        BedrockDataValueEntry(id: 14, identifier: "minecraft:gold_ore", displayName: "gold ore"),
        BedrockDataValueEntry(id: 15, identifier: "minecraft:iron_ore", displayName: "iron ore"),
        BedrockDataValueEntry(id: 16, identifier: "minecraft:coal_ore", displayName: "coal ore"),
        BedrockDataValueEntry(id: 17, identifier: "minecraft:log", displayName: "log"),
        BedrockDataValueEntry(id: 18, identifier: "minecraft:leaves", displayName: "leaves"),
        BedrockDataValueEntry(id: 19, identifier: "minecraft:sponge", displayName: "sponge"),
        BedrockDataValueEntry(id: 20, identifier: "minecraft:glass", displayName: "glass"),
        BedrockDataValueEntry(id: 21, identifier: "minecraft:lapis_ore", displayName: "lapis ore"),
        BedrockDataValueEntry(id: 22, identifier: "minecraft:lapis_block", displayName: "lapis block"),
        BedrockDataValueEntry(id: 23, identifier: "minecraft:dispenser", displayName: "dispenser"),
        BedrockDataValueEntry(id: 24, identifier: "minecraft:sandstone", displayName: "sandstone"),
        BedrockDataValueEntry(id: 25, identifier: "minecraft:noteblock", displayName: "noteblock"),
        BedrockDataValueEntry(id: 26, identifier: "minecraft:bed", displayName: "bed"),
        BedrockDataValueEntry(id: 27, identifier: "minecraft:golden_rail", displayName: "golden rail"),
        BedrockDataValueEntry(id: 28, identifier: "minecraft:detector_rail", displayName: "detector rail"),
        BedrockDataValueEntry(id: 29, identifier: "minecraft:sticky_piston", displayName: "sticky piston"),
        BedrockDataValueEntry(id: 30, identifier: "minecraft:web", displayName: "web"),
        BedrockDataValueEntry(id: 31, identifier: "minecraft:tallgrass", displayName: "tall grass"),
        BedrockDataValueEntry(id: 32, identifier: "minecraft:deadbush", displayName: "deadbush"),
        BedrockDataValueEntry(id: 33, identifier: "minecraft:piston", displayName: "piston"),
        BedrockDataValueEntry(id: 34, identifier: "minecraft:pistonArmCollision", displayName: "piston arm collision"),
        BedrockDataValueEntry(id: 35, identifier: "minecraft:wool", displayName: "wool"),
        BedrockDataValueEntry(id: 36, identifier: "minecraft:element_0", displayName: "element 0"),
        BedrockDataValueEntry(id: 37, identifier: "minecraft:yellow_flower", displayName: "yellow flower"),
        BedrockDataValueEntry(id: 38, identifier: "minecraft:red_flower", displayName: "red flower"),
        BedrockDataValueEntry(id: 39, identifier: "minecraft:brown_mushroom", displayName: "brown mushroom"),
        BedrockDataValueEntry(id: 40, identifier: "minecraft:red_mushroom", displayName: "red mushroom"),
        BedrockDataValueEntry(id: 41, identifier: "minecraft:gold_block", displayName: "gold block"),
        BedrockDataValueEntry(id: 42, identifier: "minecraft:iron_block", displayName: "iron block"),
        BedrockDataValueEntry(id: 43, identifier: "minecraft:double_stone_slab", displayName: "double stone slab"),
        BedrockDataValueEntry(id: 44, identifier: "minecraft:stone_slab", displayName: "stone slab"),
        BedrockDataValueEntry(id: 45, identifier: "minecraft:brick_block", displayName: "brick block"),
        BedrockDataValueEntry(id: 46, identifier: "minecraft:tnt", displayName: "tnt"),
        BedrockDataValueEntry(id: 47, identifier: "minecraft:bookshelf", displayName: "bookshelf"),
        BedrockDataValueEntry(id: 48, identifier: "minecraft:mossy_cobblestone", displayName: "mossy cobblestone"),
        BedrockDataValueEntry(id: 49, identifier: "minecraft:obsidian", displayName: "obsidian"),
        BedrockDataValueEntry(id: 50, identifier: "minecraft:torch", displayName: "torch"),
        BedrockDataValueEntry(id: 51, identifier: "minecraft:fire", displayName: "fire"),
        BedrockDataValueEntry(id: 52, identifier: "minecraft:mob_spawner", displayName: "mob spawner"),
        BedrockDataValueEntry(id: 53, identifier: "minecraft:oak_stairs", displayName: "oak stairs"),
        BedrockDataValueEntry(id: 54, identifier: "minecraft:chest", displayName: "chest"),
        BedrockDataValueEntry(id: 55, identifier: "minecraft:redstone_wire", displayName: "redstone wire"),
        BedrockDataValueEntry(id: 56, identifier: "minecraft:diamond_ore", displayName: "diamond ore"),
        BedrockDataValueEntry(id: 57, identifier: "minecraft:diamond_block", displayName: "diamond block"),
        BedrockDataValueEntry(id: 58, identifier: "minecraft:crafting_table", displayName: "crafting table"),
        BedrockDataValueEntry(id: 59, identifier: "minecraft:wheat", displayName: "wheat"),
        BedrockDataValueEntry(id: 60, identifier: "minecraft:farmland", displayName: "farmland"),
        BedrockDataValueEntry(id: 61, identifier: "minecraft:furnace", displayName: "furnace"),
        BedrockDataValueEntry(id: 62, identifier: "minecraft:lit_furnace", displayName: "lit furnace"),
        BedrockDataValueEntry(id: 63, identifier: "minecraft:standing_sign", displayName: "standing sign"),
        BedrockDataValueEntry(id: 64, identifier: "minecraft:wooden_door", displayName: "wooden door"),
        BedrockDataValueEntry(id: 65, identifier: "minecraft:ladder", displayName: "ladder"),
        BedrockDataValueEntry(id: 66, identifier: "minecraft:rail", displayName: "rail"),
        BedrockDataValueEntry(id: 67, identifier: "minecraft:stone_stairs", displayName: "stone stairs"),
        BedrockDataValueEntry(id: 68, identifier: "minecraft:wall_sign", displayName: "wall sign"),
        BedrockDataValueEntry(id: 69, identifier: "minecraft:lever", displayName: "lever"),
        BedrockDataValueEntry(id: 70, identifier: "minecraft:stone_pressure_plate", displayName: "stone pressure plate"),
        BedrockDataValueEntry(id: 71, identifier: "minecraft:iron_door", displayName: "iron door"),
        BedrockDataValueEntry(id: 72, identifier: "minecraft:wooden_pressure_plate", displayName: "wooden pressure plate"),
        BedrockDataValueEntry(id: 73, identifier: "minecraft:redstone_ore", displayName: "redstone ore"),
        BedrockDataValueEntry(id: 74, identifier: "minecraft:lit_redstone_ore", displayName: "lit redstone ore"),
        BedrockDataValueEntry(id: 75, identifier: "minecraft:unlit_redstone_torch", displayName: "unlit redstone torch"),
        BedrockDataValueEntry(id: 76, identifier: "minecraft:redstone_torch", displayName: "redstone torch"),
        BedrockDataValueEntry(id: 77, identifier: "minecraft:stone_button", displayName: "stone button"),
        BedrockDataValueEntry(id: 78, identifier: "minecraft:snow_layer", displayName: "snow layer"),
        BedrockDataValueEntry(id: 79, identifier: "minecraft:ice", displayName: "ice"),
        BedrockDataValueEntry(id: 80, identifier: "minecraft:snow", displayName: "snow"),
        BedrockDataValueEntry(id: 81, identifier: "minecraft:cactus", displayName: "cactus"),
        BedrockDataValueEntry(id: 82, identifier: "minecraft:clay", displayName: "clay"),
        BedrockDataValueEntry(id: 83, identifier: "minecraft:reeds", displayName: "reeds"),
        BedrockDataValueEntry(id: 84, identifier: "minecraft:jukebox", displayName: "jukebox"),
        BedrockDataValueEntry(id: 85, identifier: "minecraft:fence", displayName: "fence"),
        BedrockDataValueEntry(id: 86, identifier: "minecraft:pumpkin", displayName: "pumpkin"),
        BedrockDataValueEntry(id: 87, identifier: "minecraft:netherrack", displayName: "netherrack"),
        BedrockDataValueEntry(id: 88, identifier: "minecraft:soul_sand", displayName: "soul sand"),
        BedrockDataValueEntry(id: 89, identifier: "minecraft:glowstone", displayName: "glowstone"),
        BedrockDataValueEntry(id: 90, identifier: "minecraft:portal", displayName: "portal"),
        BedrockDataValueEntry(id: 91, identifier: "minecraft:lit_pumpkin", displayName: "lit pumpkin"),
        BedrockDataValueEntry(id: 92, identifier: "minecraft:cake", displayName: "cake"),
        BedrockDataValueEntry(id: 93, identifier: "minecraft:unpowered_repeater", displayName: "unpowered repeater"),
        BedrockDataValueEntry(id: 94, identifier: "minecraft:powered_repeater", displayName: "powered repeater"),
        BedrockDataValueEntry(id: 95, identifier: "minecraft:invisibleBedrock", displayName: "invisible bedrock"),
        BedrockDataValueEntry(id: 96, identifier: "minecraft:trapdoor", displayName: "trapdoor"),
        BedrockDataValueEntry(id: 97, identifier: "minecraft:monster_egg", displayName: "monster egg"),
        BedrockDataValueEntry(id: 98, identifier: "minecraft:stonebrick", displayName: "stone bricks"),
        BedrockDataValueEntry(id: 99, identifier: "minecraft:brown_mushroom_block", displayName: "brown mushroom block"),
        BedrockDataValueEntry(id: 100, identifier: "minecraft:red_mushroom_block", displayName: "red mushroom block"),
        BedrockDataValueEntry(id: 101, identifier: "minecraft:iron_bars", displayName: "iron bars"),
        BedrockDataValueEntry(id: 102, identifier: "minecraft:glass_pane", displayName: "glass pane"),
        BedrockDataValueEntry(id: 103, identifier: "minecraft:melon_block", displayName: "melon block"),
        BedrockDataValueEntry(id: 104, identifier: "minecraft:pumpkin_stem", displayName: "pumpkin stem"),
        BedrockDataValueEntry(id: 105, identifier: "minecraft:melon_stem", displayName: "melon stem"),
        BedrockDataValueEntry(id: 106, identifier: "minecraft:vine", displayName: "vine"),
        BedrockDataValueEntry(id: 107, identifier: "minecraft:fence_gate", displayName: "fence gate"),
        BedrockDataValueEntry(id: 108, identifier: "minecraft:brick_stairs", displayName: "brick stairs"),
        BedrockDataValueEntry(id: 109, identifier: "minecraft:stone_brick_stairs", displayName: "stone brick stairs"),
        BedrockDataValueEntry(id: 110, identifier: "minecraft:mycelium", displayName: "mycelium"),
        BedrockDataValueEntry(id: 111, identifier: "minecraft:waterlily", displayName: "waterlily"),
        BedrockDataValueEntry(id: 112, identifier: "minecraft:nether_brick", displayName: "nether brick"),
        BedrockDataValueEntry(id: 113, identifier: "minecraft:nether_brick_fence", displayName: "nether brick fence"),
        BedrockDataValueEntry(id: 114, identifier: "minecraft:nether_brick_stairs", displayName: "nether brick stairs"),
        BedrockDataValueEntry(id: 115, identifier: "minecraft:nether_wart", displayName: "nether wart"),
        BedrockDataValueEntry(id: 116, identifier: "minecraft:enchanting_table", displayName: "enchanting table"),
        BedrockDataValueEntry(id: 117, identifier: "minecraft:brewing_stand", displayName: "brewing stand"),
        BedrockDataValueEntry(id: 118, identifier: "minecraft:cauldron", displayName: "cauldron"),
        BedrockDataValueEntry(id: 119, identifier: "minecraft:end_portal", displayName: "end portal"),
        BedrockDataValueEntry(id: 120, identifier: "minecraft:end_portal_frame", displayName: "end portal frame"),
        BedrockDataValueEntry(id: 121, identifier: "minecraft:end_stone", displayName: "end stone"),
        BedrockDataValueEntry(id: 122, identifier: "minecraft:dragon_egg", displayName: "dragon egg"),
        BedrockDataValueEntry(id: 123, identifier: "minecraft:redstone_lamp", displayName: "redstone lamp"),
        BedrockDataValueEntry(id: 124, identifier: "minecraft:lit_redstone_lamp", displayName: "lit redstone lamp"),
        BedrockDataValueEntry(id: 125, identifier: "minecraft:dropper", displayName: "dropper"),
        BedrockDataValueEntry(id: 126, identifier: "minecraft:activator_rail", displayName: "activator rail"),
        BedrockDataValueEntry(id: 127, identifier: "minecraft:cocoa", displayName: "cocoa"),
        BedrockDataValueEntry(id: 128, identifier: "minecraft:sandstone_stairs", displayName: "sandstone stairs"),
        BedrockDataValueEntry(id: 129, identifier: "minecraft:emerald_ore", displayName: "emerald ore"),
        BedrockDataValueEntry(id: 130, identifier: "minecraft:ender_chest", displayName: "ender chest"),
        BedrockDataValueEntry(id: 131, identifier: "minecraft:tripwire_hook", displayName: "tripwire hook"),
        BedrockDataValueEntry(id: 132, identifier: "minecraft:tripWire", displayName: "tripwire"),
        BedrockDataValueEntry(id: 133, identifier: "minecraft:emerald_block", displayName: "emerald block"),
        BedrockDataValueEntry(id: 134, identifier: "minecraft:spruce_stairs", displayName: "spruce stairs"),
        BedrockDataValueEntry(id: 135, identifier: "minecraft:birch_stairs", displayName: "birch stairs"),
        BedrockDataValueEntry(id: 136, identifier: "minecraft:jungle_stairs", displayName: "jungle stairs"),
        BedrockDataValueEntry(id: 137, identifier: "minecraft:command_block", displayName: "command block"),
        BedrockDataValueEntry(id: 138, identifier: "minecraft:beacon", displayName: "beacon"),
        BedrockDataValueEntry(id: 139, identifier: "minecraft:cobblestone_wall", displayName: "cobblestone wall"),
        BedrockDataValueEntry(id: 140, identifier: "minecraft:flower_pot", displayName: "flower pot"),
        BedrockDataValueEntry(id: 141, identifier: "minecraft:carrots", displayName: "carrots"),
        BedrockDataValueEntry(id: 142, identifier: "minecraft:potatoes", displayName: "potatoes"),
        BedrockDataValueEntry(id: 143, identifier: "minecraft:wooden_button", displayName: "wooden button"),
        BedrockDataValueEntry(id: 144, identifier: "minecraft:skull", displayName: "skull"),
        BedrockDataValueEntry(id: 145, identifier: "minecraft:anvil", displayName: "anvil"),
        BedrockDataValueEntry(id: 146, identifier: "minecraft:trapped_chest", displayName: "trapped chest"),
        BedrockDataValueEntry(id: 147, identifier: "minecraft:light_weighted_pressure_plate", displayName: "light weighted pressure plate"),
        BedrockDataValueEntry(id: 148, identifier: "minecraft:heavy_weighted_pressure_plate", displayName: "heavy weighted pressure plate"),
        BedrockDataValueEntry(id: 149, identifier: "minecraft:unpowered_comparator", displayName: "unpowered comparator"),
        BedrockDataValueEntry(id: 150, identifier: "minecraft:powered_comparator", displayName: "powered comparator"),
        BedrockDataValueEntry(id: 151, identifier: "minecraft:daylight_detector", displayName: "daylight detector"),
        BedrockDataValueEntry(id: 152, identifier: "minecraft:redstone_block", displayName: "redstone block"),
        BedrockDataValueEntry(id: 153, identifier: "minecraft:quartz_ore", displayName: "quartz ore"),
        BedrockDataValueEntry(id: 154, identifier: "minecraft:hopper", displayName: "hopper"),
        BedrockDataValueEntry(id: 155, identifier: "minecraft:quartz_block", displayName: "quartz block"),
        BedrockDataValueEntry(id: 156, identifier: "minecraft:quartz_stairs", displayName: "quartz stairs"),
        BedrockDataValueEntry(id: 157, identifier: "minecraft:double_wooden_slab", displayName: "double wooden slab"),
        BedrockDataValueEntry(id: 158, identifier: "minecraft:wooden_slab", displayName: "wooden slab"),
        BedrockDataValueEntry(id: 159, identifier: "minecraft:stained_hardened_clay", displayName: "stained hardened clay"),
        BedrockDataValueEntry(id: 160, identifier: "minecraft:stained_glass_pane", displayName: "stained glass pane"),
        BedrockDataValueEntry(id: 161, identifier: "minecraft:leaves2", displayName: "leaves 2"),
        BedrockDataValueEntry(id: 162, identifier: "minecraft:log2", displayName: "log 2"),
        BedrockDataValueEntry(id: 163, identifier: "minecraft:acacia_stairs", displayName: "acacia stairs"),
        BedrockDataValueEntry(id: 164, identifier: "minecraft:dark_oak_stairs", displayName: "dark oak stairs"),
        BedrockDataValueEntry(id: 165, identifier: "minecraft:slime", displayName: "slime"),
        BedrockDataValueEntry(id: 166, identifier: "minecraft:unused_166", displayName: "未使用"),
        BedrockDataValueEntry(id: 167, identifier: "minecraft:iron_trapdoor", displayName: "iron trapdoor"),
        BedrockDataValueEntry(id: 168, identifier: "minecraft:prismarine", displayName: "prismarine"),
        BedrockDataValueEntry(id: 169, identifier: "minecraft:seaLantern", displayName: "sea lantern"),
        BedrockDataValueEntry(id: 170, identifier: "minecraft:hay_block", displayName: "hay block"),
        BedrockDataValueEntry(id: 171, identifier: "minecraft:carpet", displayName: "carpet"),
        BedrockDataValueEntry(id: 172, identifier: "minecraft:hardened_clay", displayName: "hardened clay"),
        BedrockDataValueEntry(id: 173, identifier: "minecraft:coal_block", displayName: "coal block"),
        BedrockDataValueEntry(id: 174, identifier: "minecraft:packed_ice", displayName: "packed ice"),
        BedrockDataValueEntry(id: 175, identifier: "minecraft:double_plant", displayName: "double plant"),
        BedrockDataValueEntry(id: 176, identifier: "minecraft:standing_banner", displayName: "standing banner"),
        BedrockDataValueEntry(id: 177, identifier: "minecraft:wall_banner", displayName: "wall banner"),
        BedrockDataValueEntry(id: 178, identifier: "minecraft:daylight_detector_inverted", displayName: "daylight detector inverted"),
        BedrockDataValueEntry(id: 179, identifier: "minecraft:red_sandstone", displayName: "red sandstone"),
        BedrockDataValueEntry(id: 180, identifier: "minecraft:red_sandstone_stairs", displayName: "red sandstone stairs"),
        BedrockDataValueEntry(id: 181, identifier: "minecraft:double_stone_slab2", displayName: "double stone slab 2"),
        BedrockDataValueEntry(id: 182, identifier: "minecraft:stone_slab2", displayName: "stone slab 2"),
        BedrockDataValueEntry(id: 183, identifier: "minecraft:spruce_fence_gate", displayName: "spruce fence gate"),
        BedrockDataValueEntry(id: 184, identifier: "minecraft:birch_fence_gate", displayName: "birch fence gate"),
        BedrockDataValueEntry(id: 185, identifier: "minecraft:jungle_fence_gate", displayName: "jungle fence gate"),
        BedrockDataValueEntry(id: 186, identifier: "minecraft:dark_oak_fence_gate", displayName: "dark oak fence gate"),
        BedrockDataValueEntry(id: 187, identifier: "minecraft:acacia_fence_gate", displayName: "acacia fence gate"),
        BedrockDataValueEntry(id: 188, identifier: "minecraft:repeating_command_block", displayName: "repeating command block"),
        BedrockDataValueEntry(id: 189, identifier: "minecraft:chain_command_block", displayName: "chain command block"),
        BedrockDataValueEntry(id: 190, identifier: "minecraft:hard_glass_pane", displayName: "hard glass pane"),
        BedrockDataValueEntry(id: 191, identifier: "minecraft:hard_stained_glass_pane", displayName: "hard stained glass pane"),
        BedrockDataValueEntry(id: 192, identifier: "minecraft:chemical_heat", displayName: "chemical heat"),
        BedrockDataValueEntry(id: 193, identifier: "minecraft:spruce_door", displayName: "spruce door"),
        BedrockDataValueEntry(id: 194, identifier: "minecraft:birch_door", displayName: "birch door"),
        BedrockDataValueEntry(id: 195, identifier: "minecraft:jungle_door", displayName: "jungle door"),
        BedrockDataValueEntry(id: 196, identifier: "minecraft:acacia_door", displayName: "acacia door"),
        BedrockDataValueEntry(id: 197, identifier: "minecraft:dark_oak_door", displayName: "dark oak door"),
        BedrockDataValueEntry(id: 198, identifier: "minecraft:grass_path", displayName: "grass path"),
        BedrockDataValueEntry(id: 199, identifier: "minecraft:frame", displayName: "frame"),
        BedrockDataValueEntry(id: 200, identifier: "minecraft:chorus_flower", displayName: "chorus flower"),
        BedrockDataValueEntry(id: 201, identifier: "minecraft:purpur_block", displayName: "purpur block"),
        BedrockDataValueEntry(id: 202, identifier: "minecraft:colored_torch_rg", displayName: "colored torch RG"),
        BedrockDataValueEntry(id: 203, identifier: "minecraft:purpur_stairs", displayName: "purpur stairs"),
        BedrockDataValueEntry(id: 204, identifier: "minecraft:colored_torch_bp", displayName: "colored torch BP"),
        BedrockDataValueEntry(id: 205, identifier: "minecraft:undyed_shulker_box", displayName: "undyed shulker box"),
        BedrockDataValueEntry(id: 206, identifier: "minecraft:end_bricks", displayName: "end bricks"),
        BedrockDataValueEntry(id: 207, identifier: "minecraft:frosted_ice", displayName: "frosted ice"),
        BedrockDataValueEntry(id: 208, identifier: "minecraft:end_rod", displayName: "end rod"),
        BedrockDataValueEntry(id: 209, identifier: "minecraft:end_gateway", displayName: "end gateway"),
        BedrockDataValueEntry(id: 210, identifier: "minecraft:allow", displayName: "allow"),
        BedrockDataValueEntry(id: 211, identifier: "minecraft:deny", displayName: "deny"),
        BedrockDataValueEntry(id: 212, identifier: "minecraft:border_block", displayName: "border block"),
        BedrockDataValueEntry(id: 213, identifier: "minecraft:magma", displayName: "magma"),
        BedrockDataValueEntry(id: 214, identifier: "minecraft:nether_wart_block", displayName: "nether wart block"),
        BedrockDataValueEntry(id: 215, identifier: "minecraft:red_nether_brick", displayName: "red nether brick"),
        BedrockDataValueEntry(id: 216, identifier: "minecraft:bone_block", displayName: "bone block"),
        BedrockDataValueEntry(id: 217, identifier: "minecraft:structure_void", displayName: "structure void"),
        BedrockDataValueEntry(id: 218, identifier: "minecraft:shulker_box", displayName: "shulker box"),
        BedrockDataValueEntry(id: 219, identifier: "minecraft:purple_glazed_terracotta", displayName: "purple glazed terracotta"),
        BedrockDataValueEntry(id: 220, identifier: "minecraft:white_glazed_terracotta", displayName: "white glazed terracotta"),
        BedrockDataValueEntry(id: 221, identifier: "minecraft:orange_glazed_terracotta", displayName: "orange glazed terracotta"),
        BedrockDataValueEntry(id: 222, identifier: "minecraft:magenta_glazed_terracotta", displayName: "magenta glazed terracotta"),
        BedrockDataValueEntry(id: 223, identifier: "minecraft:light_blue_glazed_terracotta", displayName: "light blue glazed terracotta"),
        BedrockDataValueEntry(id: 224, identifier: "minecraft:yellow_glazed_terracotta", displayName: "yellow glazed terracotta"),
        BedrockDataValueEntry(id: 225, identifier: "minecraft:lime_glazed_terracotta", displayName: "lime glazed terracotta"),
        BedrockDataValueEntry(id: 226, identifier: "minecraft:pink_glazed_terracotta", displayName: "pink glazed terracotta"),
        BedrockDataValueEntry(id: 227, identifier: "minecraft:gray_glazed_terracotta", displayName: "gray glazed terracotta"),
        BedrockDataValueEntry(id: 228, identifier: "minecraft:silver_glazed_terracotta", displayName: "silver glazed terracotta"),
        BedrockDataValueEntry(id: 229, identifier: "minecraft:cyan_glazed_terracotta", displayName: "cyan glazed terracotta"),
        BedrockDataValueEntry(id: 230, identifier: "minecraft:chalkboard", displayName: "chalkboard"),
        BedrockDataValueEntry(id: 231, identifier: "minecraft:blue_glazed_terracotta", displayName: "blue glazed terracotta"),
        BedrockDataValueEntry(id: 232, identifier: "minecraft:brown_glazed_terracotta", displayName: "brown glazed terracotta"),
        BedrockDataValueEntry(id: 233, identifier: "minecraft:green_glazed_terracotta", displayName: "green glazed terracotta"),
        BedrockDataValueEntry(id: 234, identifier: "minecraft:red_glazed_terracotta", displayName: "red glazed terracotta"),
        BedrockDataValueEntry(id: 235, identifier: "minecraft:black_glazed_terracotta", displayName: "black glazed terracotta"),
        BedrockDataValueEntry(id: 236, identifier: "minecraft:concrete", displayName: "concrete"),
        BedrockDataValueEntry(id: 237, identifier: "minecraft:concretePowder", displayName: "concrete powder"),
        BedrockDataValueEntry(id: 238, identifier: "minecraft:chemistry_table", displayName: "chemistry table"),
        BedrockDataValueEntry(id: 239, identifier: "minecraft:underwater_torch", displayName: "underwater torch"),
        BedrockDataValueEntry(id: 240, identifier: "minecraft:chorus_plant", displayName: "chorus plant"),
        BedrockDataValueEntry(id: 241, identifier: "minecraft:stained_glass", displayName: "stained glass"),
        BedrockDataValueEntry(id: 242, identifier: "minecraft:camera", displayName: "camera"),
        BedrockDataValueEntry(id: 243, identifier: "minecraft:podzol", displayName: "podzol"),
        BedrockDataValueEntry(id: 244, identifier: "minecraft:beetroot", displayName: "beetroot"),
        BedrockDataValueEntry(id: 245, identifier: "minecraft:stonecutter", displayName: "stonecutter"),
        BedrockDataValueEntry(id: 246, identifier: "minecraft:glowingobsidian", displayName: "glowingobsidian"),
        BedrockDataValueEntry(id: 247, identifier: "minecraft:netherreactor", displayName: "netherreactor"),
        BedrockDataValueEntry(id: 248, identifier: "minecraft:info_update", displayName: "info update"),
        BedrockDataValueEntry(id: 249, identifier: "minecraft:info_update2", displayName: "info update2"),
        BedrockDataValueEntry(id: 250, identifier: "minecraft:movingBlock", displayName: "moving block"),
        BedrockDataValueEntry(id: 251, identifier: "minecraft:observer", displayName: "observer"),
        BedrockDataValueEntry(id: 252, identifier: "minecraft:structure_block", displayName: "structure block"),
        BedrockDataValueEntry(id: 253, identifier: "minecraft:hard_glass", displayName: "hard glass"),
        BedrockDataValueEntry(id: 254, identifier: "minecraft:hard_stained_glass", displayName: "hard stained glass"),
        BedrockDataValueEntry(id: 255, identifier: "minecraft:reserved6", displayName: "reserved6"),
    ]

    private static let entriesByID: [Int: BedrockDataValueEntry] = {
        Dictionary(uniqueKeysWithValues: blocks.map { ($0.id, $0) })
    }()

    private static let entriesByIdentifier: [String: BedrockDataValueEntry] = {
        var result = Dictionary(uniqueKeysWithValues: blocks.map { ($0.identifier.lowercased(), $0) })
        let aliases: [String: Int] = [
            // Modern/flatter names and common aliases for the legacy families.
            "minecraft:grass_block": 2,
            "minecraft:oak_planks": 5,
            "minecraft:oak_sapling": 6,
            "minecraft:oak_log": 17,
            "minecraft:oak_leaves": 18,
            "minecraft:short_grass": 31,
            "minecraft:piston_arm_collision": 34,
            "minecraft:white_wool": 35,
            "minecraft:dandelion": 37,
            "minecraft:poppy": 38,
            "minecraft:smooth_stone_double_slab": 43,
            "minecraft:smooth_stone_slab": 44,
            "minecraft:oak_fence": 85,
            "minecraft:invisible_bedrock": 95,
            "minecraft:infested_stone": 97,
            "minecraft:stone_bricks": 98,
            "minecraft:oak_fence_gate": 107,
            "minecraft:lily_pad": 111,
            "minecraft:trip_wire": 132,
            "minecraft:skeleton_skull": 144,
            "minecraft:oak_double_slab": 157,
            "minecraft:oak_slab": 158,
            "minecraft:white_terracotta": 159,
            "minecraft:white_stained_glass_pane": 160,
            "minecraft:acacia_leaves": 161,
            "minecraft:acacia_log": 162,
            "minecraft:sea_lantern": 169,
            "minecraft:white_carpet": 171,
            "minecraft:sunflower": 175,
            "minecraft:red_sandstone_double_slab": 181,
            "minecraft:red_sandstone_slab": 182,
            "minecraft:hard_white_stained_glass_pane": 191,
            "minecraft:dirt_path": 198,
            "minecraft:item_frame": 199,
            "minecraft:colored_torch_red": 202,
            "minecraft:colored_torch_blue": 204,
            "minecraft:undyed_shulker_box": 205,
            "minecraft:white_shulker_box": 218,
            "minecraft:white_concrete": 236,
            "minecraft:white_concrete_powder": 237,
            "minecraft:compound_creator": 238,
            "minecraft:white_stained_glass": 241,
            "minecraft:moving_block": 250,
            "minecraft:hard_white_stained_glass": 254,
        ]
        for (alias, id) in aliases {
            if let entry = entriesByID[id] { result[alias.lowercased()] = entry }
        }
        return result
    }()

    static func block(forNumericID id: Int) -> BedrockDataValueEntry? {
        entriesByID[id]
    }

    static func block(forIdentifier identifier: String) -> BedrockDataValueEntry? {
        let normalized = normalizedIdentifier(identifier)
        return entriesByIdentifier[normalized]
    }

    static func identifier(forNumericID id: UInt16) -> String? {
        block(forNumericID: Int(id))?.identifier
    }

    static func numericID(forIdentifier identifier: String) -> UInt16? {
        guard let id = block(forIdentifier: identifier)?.id else { return nil }
        return UInt16(exactly: id)
    }

    static func blockIdentifier(forRawValue rawValue: String) -> String? {
        let value = rawValue.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !value.isEmpty else { return nil }
        if let decimal = Int(value), let entry = block(forNumericID: decimal) { return entry.identifier }
        if value.lowercased().hasPrefix("0x"),
           let hexadecimal = Int(value.dropFirst(2), radix: 16),
           let entry = block(forNumericID: hexadecimal) { return entry.identifier }
        return block(forIdentifier: value)?.identifier ?? normalizedIdentifier(value)
    }

    static func searchText(for state: BedrockBlockState) -> String {
        var values = [state.name]
        if let id = state.legacyID {
            values.append(String(id))
            values.append(String(format: "0x%02X", id))
            values.append("legacy:\(id):\(state.legacyData ?? 0)")
            if let entry = block(forNumericID: Int(id)) {
                values.append(entry.identifier)
                values.append(entry.displayName)
            }
        } else if let entry = block(forIdentifier: state.name) {
            values.append(String(entry.id))
            values.append(entry.hexadecimalID)
            values.append(entry.displayName)
        }
        return values.joined(separator: "\n")
    }

    private static func normalizedIdentifier(_ identifier: String) -> String {
        let trimmed = identifier.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        guard !trimmed.isEmpty else { return trimmed }
        return trimmed.contains(":") ? trimmed : "minecraft:\(trimmed)"
    }
}
