namespace MCBEEditor.Core.Entity;

public static class BedrockEntityCatalog
{
    private static readonly IReadOnlyDictionary<long, string> ByNumericId = new Dictionary<long, string>
    {
        [1L] = "minecraft:undefined_test_only",
        [10L] = "minecraft:chicken",
        [11L] = "minecraft:cow",
        [12L] = "minecraft:pig",
        [13L] = "minecraft:sheep",
        [14L] = "minecraft:wolf",
        [15L] = "minecraft:villager",
        [16L] = "minecraft:mooshroom",
        [17L] = "minecraft:squid",
        [18L] = "minecraft:rabbit",
        [19L] = "minecraft:bat",
        [20L] = "minecraft:iron_golem",
        [21L] = "minecraft:snow_golem",
        [22L] = "minecraft:ocelot",
        [23L] = "minecraft:horse",
        [24L] = "minecraft:donkey",
        [25L] = "minecraft:mule",
        [26L] = "minecraft:skeleton_horse",
        [27L] = "minecraft:zombie_horse",
        [28L] = "minecraft:polar_bear",
        [29L] = "minecraft:llama",
        [30L] = "minecraft:parrot",
        [31L] = "minecraft:dolphin",
        [32L] = "minecraft:zombie",
        [33L] = "minecraft:creeper",
        [34L] = "minecraft:skeleton",
        [35L] = "minecraft:spider",
        [36L] = "minecraft:zombie_pigman",
        [37L] = "minecraft:slime",
        [38L] = "minecraft:enderman",
        [39L] = "minecraft:silverfish",
        [40L] = "minecraft:cave_spider",
        [41L] = "minecraft:ghast",
        [42L] = "minecraft:magma_cube",
        [43L] = "minecraft:blaze",
        [44L] = "minecraft:zombie_villager",
        [45L] = "minecraft:witch",
        [46L] = "minecraft:stray",
        [47L] = "minecraft:husk",
        [48L] = "minecraft:wither_skeleton",
        [49L] = "minecraft:guardian",
        [50L] = "minecraft:elder_guardian",
        [51L] = "minecraft:npc",
        [52L] = "minecraft:wither",
        [53L] = "minecraft:ender_dragon",
        [54L] = "minecraft:shulker",
        [55L] = "minecraft:endermite",
        [56L] = "minecraft:agent",
        [57L] = "minecraft:vindicator",
        [58L] = "minecraft:phantom",
        [59L] = "minecraft:ravager",
        [61L] = "minecraft:armor_stand",
        [62L] = "minecraft:tripod_camera",
        [63L] = "minecraft:player",
        [64L] = "minecraft:item",
        [65L] = "minecraft:tnt",
        [66L] = "minecraft:falling_block",
        [67L] = "minecraft:moving_block",
        [68L] = "minecraft:xp_bottle",
        [69L] = "minecraft:xp_orb",
        [70L] = "minecraft:eye_of_ender_signal",
        [71L] = "minecraft:ender_crystal",
        [72L] = "minecraft:fireworks_rocket",
        [73L] = "minecraft:thrown_trident",
        [74L] = "minecraft:turtle",
        [75L] = "minecraft:cat",
        [76L] = "minecraft:shulker_bullet",
        [77L] = "minecraft:fishing_hook",
        [78L] = "minecraft:chalkboard",
        [79L] = "minecraft:dragon_fireball",
        [80L] = "minecraft:arrow",
        [81L] = "minecraft:snowball",
        [82L] = "minecraft:egg",
        [83L] = "minecraft:painting",
        [84L] = "minecraft:minecart",
        [85L] = "minecraft:fireball",
        [86L] = "minecraft:splash_potion",
        [87L] = "minecraft:ender_pearl",
        [88L] = "minecraft:leash_knot",
        [89L] = "minecraft:wither_skull",
        [90L] = "minecraft:boat",
        [91L] = "minecraft:wither_skull_dangerous",
        [93L] = "minecraft:lightning_bolt",
        [94L] = "minecraft:small_fireball",
        [95L] = "minecraft:area_effect_cloud",
        [96L] = "minecraft:hopper_minecart",
        [97L] = "minecraft:tnt_minecart",
        [98L] = "minecraft:chest_minecart",
        [100L] = "minecraft:command_block_minecart",
        [101L] = "minecraft:lingering_potion",
        [102L] = "minecraft:llama_spit",
        [103L] = "minecraft:evocation_fang",
        [104L] = "minecraft:evocation_illager",
        [105L] = "minecraft:vex",
        [106L] = "minecraft:ice_bomb",
        [107L] = "minecraft:balloon",
        [108L] = "minecraft:pufferfish",
        [109L] = "minecraft:salmon",
        [110L] = "minecraft:drowned",
        [111L] = "minecraft:tropicalfish",
        [112L] = "minecraft:cod",
        [113L] = "minecraft:panda",
        [114L] = "minecraft:pillager",
        [115L] = "minecraft:villager_v2",
        [116L] = "minecraft:zombie_villager_v2",
        [117L] = "minecraft:shield",
        [118L] = "minecraft:wandering_trader",
        [120L] = "minecraft:elder_guardian_ghost",
        [121L] = "minecraft:fox",
        [122L] = "minecraft:bee",
        [123L] = "minecraft:piglin",
        [124L] = "minecraft:hoglin",
        [125L] = "minecraft:strider",
        [126L] = "minecraft:zoglin",
        [127L] = "minecraft:piglin_brute",
        [128L] = "minecraft:goat",
        [129L] = "minecraft:glow_squid",
        [130L] = "minecraft:axolotl",
        [131L] = "minecraft:warden",
        [132L] = "minecraft:frog",
        [133L] = "minecraft:tadpole",
        [134L] = "minecraft:allay",
        [138L] = "minecraft:camel",
        [139L] = "minecraft:sniffer",
        [140L] = "minecraft:breeze",
        [141L] = "minecraft:breeze_wind_charge_projectile",
        [142L] = "minecraft:armadillo",
        [143L] = "minecraft:wind_charge_projectile",
        [144L] = "minecraft:bogged",
        [145L] = "minecraft:ominous_item_spawner",
        [146L] = "minecraft:creaking",
        [147L] = "minecraft:happy_ghast",
        [148L] = "minecraft:copper_golem",
        [149L] = "minecraft:nautilus",
        [150L] = "minecraft:zombie_nautilus",
        [151L] = "minecraft:parched",
        [152L] = "minecraft:camel_husk",
        [153L] = "minecraft:sulfur_cube",
        [154L] = "minecraft:cushion",
        [157L] = "minecraft:trader_llama",
        [218L] = "minecraft:chest_boat",
    };

    private static readonly IReadOnlyDictionary<string, long> ByIdentifier = ByNumericId
        .GroupBy(pair => pair.Value, StringComparer.OrdinalIgnoreCase)
        .ToDictionary(group => group.Key, group => group.First().Key, StringComparer.OrdinalIgnoreCase);

    public static string? IdentifierForNumericId(long id) => ByNumericId.TryGetValue(id, out var value) ? value : null;

    public static long? NumericIdForIdentifier(string identifier)
    {
        if (string.IsNullOrWhiteSpace(identifier)) return null;
        var normalized = identifier.Trim();
        if (!normalized.Contains(':')) normalized = "minecraft:" + normalized;
        return ByIdentifier.TryGetValue(normalized, out var value) ? value : null;
    }
}
